language: scala
scala:
  - 2.12.12
  - 2.13.4

env:
  matrix:
    - TRAVIS_JDK=adopt@1.8.0-242
    - TRAVIS_JDK=adopt@1.11.0-6

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use "$_" && java -Xmx32m -version

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.gradle
    - $HOME/.jabba/jdk

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test docs/paradox

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

