language: scala
scala:
  - 2.12.8
  - 2.13.1

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.1/install.sh | bash && . ~/.jabba/jabba.sh
  - jabba install adopt@~1.8.0-222

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.jabba/jdk
    - $HOME/.cache/coursier

script:
  - jabba use ${JDK:=adopt@~1.8.0-222}
  - java -version
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test docs/paradox

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
